config/routes.rb
Rails.application.routes.draw do
  resources :answers, only: []
  resources :contents
  resources :dashboard, only: :show
  resources :users, only: [:index, :edit, :update]
  devise_for :users

  authenticated :user do
    root to: 'dashboard#show'
  end

  root to: redirect('/users/sign_in')
end

app/models/answer.rb
# Class for answers to question type contents
class Answer < ApplicationRecord
  belongs_to :content, optional: true

  def to_s
    text
  end
end

app/models/application_record.rb
# Is this file needed? TODO Test deleting it
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
# Class with primary live content
class Content < ApplicationRecord
  belongs_to :next, dependent: :destroy, optional: true, class_name: Content
  has_many :answers, dependent: :destroy

  attr_accessor :create_next
  attr_accessor :previous_id
  accepts_nested_attributes_for :answers

  validates :key, presence: true

  enum category: [
    :question,
    :explanation
  ]

  enum section: [
    :introduction,
    :number_system,
    :geometry
  ]

  def to_s
    key
  end
end

app/models/user.rb
# Devise user model, overriding to enable roles
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [
    :default,
    :admin
  ]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
# Default application controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
# Controller for primary contents
class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Content.where(category: Content.categories['question'])
    @explanations = Content.where(category: Content.categories['explanation'])
    @section = t('dashboard.show.admin_dashboard')
  end

  def show
    @selected = params[:selected] || -1
    @previous = Content.where(next: @content.id).first
    @options = @content.answers.pluck(:text)
  end

  def new
    @content = Content.new
    @others = Content.all
    @previous_id = params[:previous_id]

    4.times { @content.answers.build } unless @content.answers.length.positive?
  end

  def edit
    @others = Content.where.not(id: @content.id)
    4.times { @content.answers.build } unless @content.answers.length.positive?
  end

  def create
    @content = Content.new(content_params)
    @content[:next_id] = nil if content_params[:next_id].empty?

    if @content.save
      update_previous
      successful_save('success.create')
    else
      render :new
    end
  end

  def update
    if @content.update(content_params)
      successful_save('success.update')
    else
      render :edit
    end
  end

  def destroy
    # Only delete this record, not any related ones
    @content.next_id = ''
    @content.destroy
    redirect_to contents_url, notice: t('success.destroy', name: @content.key)
  end

  private

  def update_previous
    prev_id = content_params[:previous_id]
    return if prev_id.to_i < 0
    @previous = Content.find(prev_id)
    @previous.update_attribute(:next_id, @content.id)
  end

  def successful_save(method_name)
    notice = t(method_name, name: @content.key)
    if params[:commit] == t('save')
      redirect_to contents_path, notice: notice
    else
      redirect_to new_content_path(previous_id: @content.id), notice: notice
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def content_params
    params.require(:content).permit(
      :text, :key,
      :section, :next_id,
      :category, :answers,
      :create_next, :previous_id,
      :footnotes, :background_link,
      answers_attributes: [:id, :key, :text, :score]
    )
  end
end

app/controllers/dashboard_controller.rb
# Controller for the landing page dashboard
class DashboardController < ApplicationController
  def show
    content_lowest = Content.minimum(:id)
    @content = Content.find(content_lowest)
    @section = t('.admin_dashboard')
  end
end

app/controllers/users_controller.rb
# Override devise to manage roles
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:edit, :update]

  def index
    @users = User.all
    @section = t('.title')
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: t('success.update', name: @user.email)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:role)
  end
end

app/views/contents/_answer_fields.html.erb
<div class="answer">
  <div class="right">
    <%= label_tag :score %> <%= ff.number_field :score, min: 0, max: 10, value: 5 %>
  </div>
  <div class="text">
    <%= label_tag :answer %> <%= ff.text_field :text %>
  </div>
</div>

app/views/contents/_answers.html.erb
<div class="section answers">
  <% answers.each_with_index do | text, index | %>
    <% if index.to_s == selected %>
      <h4> <%= t(".you_chose") %> <%= text %> </h4>
    <% else %>
      <div class="answer"> <%= text %> </div>
    <% end %>
  <% end %>
</div>

app/views/contents/_contents_table.html.erb
<table class="contents-table">
  <thead>
    <tr>
      <th><%= t(".id") %></th>
      <th><%= t(".key") %></th>
      <th><%= t(".next") %></th>
      <th><%= t(".actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% contents.each do |content| %>
      <tr>
        <td><%= content.id %></td>
        <td><%= link_to content.key, content_path(content) %></td>
        <td><%= content.next %></td>
        <td>
          <%= link_to "", edit_content_path(content), class: "fa fa-edit" %>
          <%= link_to "", content, method: :delete, data: { confirm: t(".sure") }, class: "fa fa-trash" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contents/_form.html.erb
<%= simple_form_for(content) do |f| %>
  <% if content.errors.any? %>
    <div class="error" id="error_explanation">
      <h2><%= t(".errors") %></h2>
      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="content row">
    <div class="col-sm-8">
      <h4><%= t(".contents") %></h4>

      <div class="col-sm-6">
        <div class="key">
          <%= label_tag :key %>
          <%= f.text_field :key, placeholder: t(".key_placeholder") %>
        </div>

        <div class="follows">
          <%= label_tag :next %>
          <%= f.collection_select :next_id, others || [], :id, :key, include_blank: true %>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="topic">
          <%= label_tag :section %>
          <%= f.select(:section, Content.sections.keys.map {|section| [section.titleize,section]}) %>
        </div>

        <div class="category">
          <%= label_tag :category %>
          <%= f.select(:category, Content.categories.keys.map {|category| [category.titleize,category]}, class: "content-category") %>
        </div>
      </div>

      <div class="text">
        <%= f.input :text, as: :ckeditor, placeholder: t(".content_placeholder"), input_html: { ckeditor: { toolbar: 'mini' } } %>
      </div>

      <div class="background">
        <%= f.input :background_link, placeholder: t(".background_placeholder") %>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="answers <%= content.category == "explanation" ? "hidden" : "" %>">
        <h4><%= t(".answers") %></h4>
        <%= f.simple_fields_for :answers do |ff| %>
          <%= render 'contents/answer_fields', ff: ff, selected: selected %>
        <% end %>
      </div>
    </div>

    <%= f.number_field :previous_id, value: previous_id, class: "hidden" %>

  </div>
  <div class="content_details row">
    <div class="col-sm-8">
      <%= content_tag(:div, "", data: {contents: content.answers}, class: "data col-md-0") %>

      <%= f.text_area :footnotes, placeholder: t(".footnote_placeholder"), class: "content-footnote" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit t("save") %>
    <%= f.submit t(".save_and_next") %>
  </div>

<% end %>

app/views/contents/edit.html.erb
<%= render 'form', content: @content, others: @others, selected: @selected, previous_id: -1 %>

app/views/contents/index.html.erb
<div class="section">
  <h3><%= t(".questions") %></h3>
  <%= render 'contents_table', contents: @questions %>

  <h3><%= t(".explanations") %></h3>
  <%= render 'contents_table', contents: @explanations %>

  <br>
  <div class="actions">
    <%= link_to t(".new"), new_content_path %>
  </div>
</div>

app/views/contents/new.html.erb
<%= render 'form', content: @content, others: @others, selected: @selected, previous_id: @previous_id || "-1" %>

app/views/contents/show.html.erb
<div class="container with-background">
  <h3><%= @content.key %></h3>

  <img src="<%= @content.background_link %>" >
  <% if @selected.to_i >= 0 %>
    <%= render "answers", selected: @selected, answers: @previous.answers %>
  <% end %>

  <% if @content.present? %>
    <%= render "components/content", content: @content, options: @options %>
  <% elsif @content.next.present? %>
    <div class="actions">
      <%= link_to @content.next, content_path(@content.next) %>
    </div>
  <% end %>
</div>

<% if current_user.admin? %>
  <div class="actions no-container">
    <%= link_to t("edit"), edit_content_path(@content), class: "left" %>
  </div>
<% end %>

app/views/dashboard/show.html.erb
<div class="container">
  <h2><%= t(".title") %></h2>

  <% if current_user.admin? %>
    <div class="actions">
      <%= link_to t(".contents"), contents_path %>
      <%= link_to t(".users"), users_path %>
    </div>
  <% else %>
    <%= render "components/content", content: @content, options: @options %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "components/header", section: @section %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2><%= t(".title", user: @user.email) %>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error" id="error_explanation">
      <h2><%= t(".errors") %></h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user">
    <label><%= t(".role") %></label>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize, role]}) %>
  </div>

  <div class="actions">
    <%= f.submit t("save") %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <table>
    <thead>
      <tr>
        <th><%= t(".email") %></th>
        <th><%= t(".role") %></th>
        <th><%= t(".actions") %></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.role.titleize %></td>
          <td>
            <%= link_to "", edit_user_path(user), class: "fa fa-edit" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>